[ADD] : Ajout du calculateur de croissance
OussamaBouhlel/nutrition_libre_addons pull request #1
Opened 2024-09-17 02:52 UTC by OussamaBouhlel

Ajout des fichiers CSS, JS et XML pour la configuration du calculateur de croissance.

2024-09-17 03:47 UTC, mathben requested changes
Merci pour cette contribution, malheureusement je n'ai pas pu le tester, voir dernier commentaire dans le fichier 
snippet_growth_calculator/views/snippet_growth_calculator_category.xml

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/__manifest__.py
> +    'license': 'LGPL-3',
Met AGPL-3 svp, c'est une meilleure license pour la communauté.

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/__manifest__.py
> +    'application': True,
Ce n'est pas encore une application.

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/__manifest__.py
> +    'version': '1.0',
Le version de ton module, c'est 16.0.1.0.0 ou réduire le 1.0.0 pour moindre. Le 16.0 reste fixé sur la version majeure d'Odoo.

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/static/src/images/bebe-yeux-bleus.jpg
As-tu les droits de publication pour cette image? D'où vient-elle?

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/static/src/js/growth_calculator.js
> +    var age = parseFloat(document.getElementById('floatingAge').value);
Il y a une autre technique que d'utiliser docuemnt.getElementById. Cela limite à un seul snippet par page puisque l'identifiant doit être unique. Cherche une autre technique pour obtenir l'information du XML

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/static/src/js/growth_calculator.js
> +        age: "L'âge doit être compris entre 0 et 60 mois.",
Il y a un outil de traduction en javascript, c'est le i18n. Des fois c'est _() et il aurait une autre technique pour le Javascript.

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/views/snippet_growth_calculator_assets.xml
> +            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/css/bootstrap.min.css"/>
Il faut que ces fichiers soient téléchargés localement, sinon ça brise la pérennité de ce code libre en forçant la dépendance à un lien qui peut briser.

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/views/snippet_growth_calculator.xml
> +                                    <canvas id="canvasIMC" style="display:none;"></canvas>
pourquoi il faut cacher le canvas dans le javascript, si ici, il est déjà caché?

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/static/src/js/growth_calculator.js
> +    canvasIMC.style.display = 'none';
Il aurait été caché dans le XML aussi, c'est quoi la différence?

2024-09-17 03:47 UTC, mathben commented on snippet_growth_calculator/views/snippet_growth_calculator_category.xml
> +        <xpath expr="//div[@id='snippets']" position="inside">
J'ai une erreur ici d'exécution à l'installation du module :
```
Element '<xpath expr="//div[@id=&#39;snippets&#39;]">' cannot be located in parent view
```
D'ailleurs, je ne trouve pas dans le code d'autre exemple similaire à ce «xpath expr»

2024-09-17 12:09 UTC, OussamaBouhlel commented on snippet_growth_calculator/static/src/images/bebe-yeux-bleus.jpg
C'est une image libre de droits.

2024-09-17 17:57 UTC, merged

2024-09-18 18:49 UTC, OussamaBouhlel commented on snippet_growth_calculator/static/src/js/growth_calculator.js
> +    canvasIMC.style.display = 'none';
Cacher le canevas en JavaScript, même s'il est déjà caché dans le HTML, permet de contrôler dynamiquement sa visibilité en fonction des interactions utilisateur et de la logique de l'application. Cela améliore les performances en évitant le rendu inutile et les opérations de dessin avant que l'élément ne soit nécessaire. Cette approche assure une gestion plus flexible et précise des éléments de l'interface utilisateur, adaptant leur visibilité aux besoins actuels de l'application.